### ISSUE TITLE
Arena add crashes

### ISSUE THREAD

**Issue by woodlegas** [woodlegas/one-vs-one#3]
*Case 1*
[19:57:17] [Server thread/INFO]: XavThePanda issued server command: /1v1 arena add end -18 137 546

org.bukkit.command.CommandException: Unhandled exception executing command '1v1' in plugin 1v1 v0.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at ca.woodleg.spigotPlugin.one_vs_one.command.OneVsOneArenaAdd.onCommand(OneVsOneArenaAdd.java:35) ~[?:?]
	at ca.woodleg.spigotPlugin.one_vs_one.command.OneVsOneArena.onCommand(OneVsOneArena.java:67) ~[?:?]
	at ca.woodleg.spigotPlugin.one_vs_one.command.Manager.onCommand(Manager.java:63) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	... 15 more

===================================
*Case 2*

[19:57:44] [Server thread/INFO]: XavThePanda issued server command: /1v1 arena add end -18 137 546 -18 137 512
[19:57:44] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command '1v1' in plugin 1v1 v0.5
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.handleCommand(PlayerConnection.java:1349) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1184) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at ca.woodleg.spigotPlugin.one_vs_one.command.OneVsOneArenaAdd.onCommand(OneVsOneArenaAdd.java:35) ~[?:?]
	at ca.woodleg.spigotPlugin.one_vs_one.command.OneVsOneArena.onCommand(OneVsOneArena.java:67) ~[?:?]
	at ca.woodleg.spigotPlugin.one_vs_one.command.Manager.onCommand(Manager.java:63) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.9.4.jar:git-Spigot-c6871e2-0cd0397]
	... 15 more

================================================

**Comment by woodlegas** [comment]
Fixed in 0.6
